version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: dotnet/sdk
    versions:
    - 5.0.102.pre.buster.pre.slim
