name: CI/CD

on:
  push:
  pull_request:

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: joshkeegan
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Format
        run: make format
      
      - name: Build
        run: make tag
      
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: make publish